# Generated by Django 4.1.6 on 2023-06-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_creator_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="enduser",
            name="required",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRONTEND", "Frontend Developers"),
                    ("BACKEND", "Backend Developers"),
                    ("FULLSTACK", "FullStack Developers"),
                    ("BLOCKCHAIN", "Blockchain Developers"),
                    ("DATA_ANALYSIS", "Data Analyst"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
