# Generated by Django 4.1.6 on 2023-06-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_enduser_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="creator",
            name="chat_room_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
