# Generated by Django 4.1.6 on 2023-06-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_chatroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creator",
            name="chat_room_name",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
    ]
