# Generated by Django 4.1.6 on 2023-06-23 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_creator_chat_room_name_delete_chatroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.creator"
                    ),
                ),
                (
                    "end_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.enduser"
                    ),
                ),
            ],
        ),
    ]
