# Generated by Django 4.1.6 on 2023-06-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_chat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chat",
        ),
    ]
