# Generated by Django 4.1.6 on 2023-06-24 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bid_price", models.PositiveIntegerField()),
                (
                    "custom_option",
                    models.CharField(
                        choices=[("CUSTOMIZE", "Custom"), ("NO_CUSTOM", "No Custom")],
                        max_length=15,
                    ),
                ),
                (
                    "bidder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main.enduser",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="main.post",
                    ),
                ),
            ],
        ),
    ]
