# Generated by Django 4.1.6 on 2023-06-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="comments",
            field=models.TextField(default="None"),
        ),
    ]
