# Generated by Django 4.1.6 on 2023-06-25 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_bid_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="main.post",
            ),
        ),
    ]
