# Generated by Django 4.1.6 on 2023-06-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_bid_bidder"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
