# Generated by Django 4.1.6 on 2023-06-25 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_post_accepted_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="accepted_bid",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.bid",
            ),
        ),
    ]
