# Generated by Django 4.1.6 on 2023-06-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_post_accepted_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
