# Generated by Django 4.1.6 on 2023-06-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_post_closed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="accepted_bid",
        ),
    ]
