# Generated by Django 4.1.6 on 2023-06-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_remove_post_accepted_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="payed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="payed",
            field=models.BooleanField(default=False),
        ),
    ]
