# Generated by Django 4.1.6 on 2023-07-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_alter_message_author_alter_message_receiver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creator",
            name="profession",
        ),
        migrations.RemoveField(
            model_name="enduser",
            name="required",
        ),
        migrations.AddField(
            model_name="creator",
            name="profession_1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRONTEND", "Frontend Dev."),
                    ("BACKEND", "Backend Dev."),
                    ("FULLSTACK", "FullStack Dev."),
                    ("BLOCKCHAIN", "Blockchain Dev."),
                    ("DATA_ANALYSIS", "Data Analyst"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="profession_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRONTEND", "Frontend Dev."),
                    ("BACKEND", "Backend Dev."),
                    ("FULLSTACK", "FullStack Dev."),
                    ("BLOCKCHAIN", "Blockchain Dev."),
                    ("DATA_ANALYSIS", "Data Analyst"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="creator",
            name="profession_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRONTEND", "Frontend Dev."),
                    ("BACKEND", "Backend Dev."),
                    ("FULLSTACK", "FullStack Dev."),
                    ("BLOCKCHAIN", "Blockchain Dev."),
                    ("DATA_ANALYSIS", "Data Analyst"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enduser",
            name="required_1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRONTEND", "Frontend Dev."),
                    ("BACKEND", "Backend Dev."),
                    ("FULLSTACK", "FullStack Dev."),
                    ("BLOCKCHAIN", "Blockchain Dev."),
                    ("DATA_ANALYSIS", "Data Analyst"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enduser",
            name="required_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRONTEND", "Frontend Dev."),
                    ("BACKEND", "Backend Dev."),
                    ("FULLSTACK", "FullStack Dev."),
                    ("BLOCKCHAIN", "Blockchain Dev."),
                    ("DATA_ANALYSIS", "Data Analyst"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enduser",
            name="required_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRONTEND", "Frontend Dev."),
                    ("BACKEND", "Backend Dev."),
                    ("FULLSTACK", "FullStack Dev."),
                    ("BLOCKCHAIN", "Blockchain Dev."),
                    ("DATA_ANALYSIS", "Data Analyst"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="field",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRONTEND", "Frontend Dev."),
                    ("BACKEND", "Backend Dev."),
                    ("FULLSTACK", "FullStack Dev."),
                    ("BLOCKCHAIN", "Blockchain Dev."),
                    ("DATA_ANALYSIS", "Data Analyst"),
                ],
                max_length=15,
                null=True,
            ),
        ),
    ]
